### ISSUE TITLE
WHY WONT WALLET LOAD

### ISSUE THREAD

**Issue by rap143** [Noso-Project/NosoWallet-Android#4]
when I open wallet it always show white screen then crashes pls fix

**Comment by Stevengez** [comment]
> when I open wallet it always show white screen then crashes pls fix

What phone and android version are you using?

**Comment by rap143** [comment]
oppo a5s and android 8.1 I've installed this app almost a year ago but won't work so I just stopped doint it this time I wanted to try it again but still won't work pls fix it

**Comment by Stevengez** [comment]
> oppo a5s and android 8.1 I've installed this app almost a year ago but won't work so I just stopped doint it this time I wanted to try it again but still won't work pls fix it

Thanks, I'll need the logs also, you can find them by going to the device storage path: /Android/data/com.s7evensoftware.nosowallet/files/NOSODATA/LOGS/error_log.txt

**Comment by rap143** [comment]
@
[error_log.txt](https://github.com/Noso-Project/NosoWallet-Android/files/8740073/error_log.txt)
here you go sorry if I replry late

**Comment by Stevengez** [comment]
> @ [error_log.txt](https://github.com/Noso-Project/NosoWallet-Android/files/8740073/error_log.txt) here you go sorry if I replry late

Thanks, I have found the issue, it will be fix in the next release.

**Comment by rap143** [comment]
thanks looking forward to it
